ProjetoIntegrado/ProjetoIntegrado/Models/Publico.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjetoIntegrado.Models
{
    public class Publico
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public string Classificacao { get; set; }
    }
}

ProjetoIntegrado/ProjetoIntegrado/Controllers/PublicoController.cs
using System.Web.Mvc;
using ProjetoIntegrado.Models;

namespace ProjetoIntegrado.Controllers
{
    public class PublicoController : Controller
    {
        // GET: Publico
        public ActionResult Index()
        {
            return View();
        }

        [Route("Evento/Publico/Cadastro")]
        public ActionResult Cadastro(Usuario usuario)
        {
            return View();
        }

        public JsonResult Result(string usuario)
        {
            var ajaxRetornoViewModel = false;

            if (!string.IsNullOrEmpty(usuario))
            {
                return new JsonResult
                {
                    Data = true,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            return new JsonResult
            {
                Data = ajaxRetornoViewModel,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }
    }
}

ProjetoIntegrado/ProjetoIntegrado/Views/Publico/Cadastro.cshtml
@model ProjetoIntegrado.Models.Publico

@{
    ViewBag.Title = "Cadastro de Público";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<h2>Cadastro de Público</h2>
<h2>Novo usuario</h2>

<label for="login">login:</label>
<input type="text" name="login" />
<br />
<label for="password">chave:</label>
<input type="text" name="senha" />
<br />
<button id="enviar">Enviar</button>

<script type="text/javascript">

    $("#enviar").click(function () {
        var button = this;
        $(button).button('loading');

        $.ajax({
            type: "GET",
            url: '@Url.Action("Result", "Publico")',
            usuario: "well",
            cache: false,
            success: function (json) {
                if (json) {
                    alert("ok");
                } else {
                    alert("x");
                }
            },
            complete: function () {
                $(button).button('reset');
            }
        });
    });
</script>

ProjetoIntegrado/ProjetoIntegrado/Views/Publico/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>title</h2>